@url = http://localhost:6000/Producto

GET {{url}}

###
GET {{url}}/1
###
POST {{url}}
Content-Type: application/json

{
    "Nombre": "",
    "Precio": "",
    "Codigo": "",
    "Existencia":""
}

###
PUT {{url}}/1
Content-Type: application/json

{
    "Nombre": "",
    "Precio": "",
    "Existencia":""
}

###
DELETE {{url}}/2
